floor_sensor_node:
  ros__parameters:
    loop_hz:          5.0
    integration_time: 0x80   # 154 ms
    gain:             60     # 1 | 4 | 16 | 60

    # HSV colour ranges — h_ranges as flat list of pairs [lo, hi, lo, hi, ...]
    color_cyan_h_ranges:    [160, 200]
    color_cyan_s:           [0.40, 1.00]
    color_cyan_v:           [0.20, 1.00]

    color_magenta_h_ranges: [0, 5, 355, 360]   # two h ranges
    color_magenta_s:        [0.90, 1.00]
    color_magenta_v:        [0.30, 0.50]

    color_yellow_h_ranges:  [15, 22]
    color_yellow_s:         [0.94, 1.00]
    color_yellow_v:         [0.15, 0.30]
